# This is a config for E2B sandbox template.
# You can use template ID (keijlkeyqbthfzgmez4y) or template name (vibe-nextjs-test2-shafi) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test2-shafi") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test2-shafi") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test2-shafi')

team_id = "ce6e1cf1-6252-4371-a5a2-bfc0b723747c"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test2-shafi"
template_id = "keijlkeyqbthfzgmez4y"
